name: Build & test all the services

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build & test all services in sub-folders
  hello-service:
    uses: api-sde/swift-shop-go-gcp/.github/workflows/service.yml@main
    with:
      serviceName: hello

  health-service:
    uses: api-sde/swift-shop-go-gcp/.github/workflows/service.yml@main
    with:
      serviceName: health

  user-service:
    uses: api-sde/swift-shop-go-gcp/.github/workflows/service.yml@main
    with:
      serviceName: user